### ISSUE TITLE
Stop stream of a single channel

### ISSUE THREAD

**Issue by shekit** [topheman/twitter-stream-channels#4]
Hey,

Is there any way to stop the stream of a single channel without affecting the other channels that might be streaming? Calling stream.stop() will close the entire stream but I'm looking to suspend the streaming of only a particular channel.

**Comment by topheman** [comment]
[From the README](https://github.com/topheman/twitter-stream-channels#twitter-stream-channels)

> This module lets you open multiple channels with there own filters, on the same stream. And then, you can add events to each of them individually, to listen to there results, like if you had open multiple streams.

You have only one stream opened to twitter which dispatches to multiple channels, so there isn't any *"stream of a single channel"* to stop. You can either:

* stop the whole stream
* stop listening to a specific channel

**Comment by shekit** [comment]
Hey, thanks for the reply. I want to stop listening to a specific channel. How exactly would I do that? Can I do stream.removeListener('channel')?

**Comment by topheman** [comment]
That's it, if you had that kind of code :

```js
function processColors(tweet) {
  //do some processing
}

stream.on('channels/colors', processColors);
```

You should be able to stop listening by doing the following (you must have the reference to `processColors` https://nodejs.org/api/events.html#events_event_removelistener : 

```js
stream.removeListener('channels/colors', processColors);
```

Not tested, but as I read my code, this is simple event subscription (see the part managing that) : https://github.com/topheman/twitter-stream-channels/blob/master/lib/StreamChannels.js#L60

**Comment by shekit** [comment]
Awesome thanks! Just trying it out now

**Comment by topheman** [comment]
Just found out I already put it on the readme when I made the module : https://github.com/topheman/twitter-stream-channels#how-to-unsubscribe- :-)
