### ISSUE TITLE
Streaming tweets by user

### ISSUE THREAD

**Issue by MDrooker** [topheman/twitter-stream-channels#7]
How can I get a stream of tweets by username?  I have tried a few different ways, but dont see them

**Comment by topheman** [comment]
You may use directly the twitter stream API : https://dev.twitter.com/streaming/userstreams

fixes #6

**Comment by MDrooker** [comment]
Ok..Sorry to be dense.  But how does that integration work with the stream-channel aggregation of this library?  My use case has terms and users being aggregated into a "channel".  

But Im not seeing how the integration with the API mentioned above works that way.

Again, sorry to be dense. I did look over the examples and the API from this module

**Comment by topheman** [comment]
`twitter-stream-channels` only handles [keywords](https://github.com/topheman/twitter-stream-channels#to-what-events-can-i-subscribe-), you may call directly the twitter api, you can use the [twit](https://github.com/ttezel/twit) client that `twitter-stream-channels` is using under the hood.
